services:
  - type: web
    name: alcaldia-de-michelena-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true